#!/usr/bin/env bash
# =============================================================================
# 05_postprocessing.sh
#
# Phase 5: Post-process BEAST output and generate publication figures.
#
# Steps:
#   1. Combine 3 independent BEAST chains (logcombiner, 20% burnin)
#      — main parameter log
#      — NeDynamics logs for all 4 demes
#      — cumulativeIncidence logs for focal demes 1–3 (Deme4 is the background deme)
#      — posterior tree distribution
#   2. Thin the combined tree file for treeannotator
#   3. Build consensus tree (treeannotator, CCD0 topology, median heights)
#   4. Generate publication figures (analyse_posteriors.py)
#
# Input: XMLfiles_cluster/beast_runs/${RUN_NAME}/
# Output: sandbox/
# =============================================================================
set -euo pipefail

# =============================================================================
# Usage
# =============================================================================
usage() {
    echo "Usage: $0 <BEAST_RUN_DIR> <OUTPUT_DIR> <STATE_TIME_CSV>"
    echo ""
    echo "  BEAST_RUN_DIR   Directory containing BEAST chain outputs"
    echo "  OUTPUT_DIR      Parent directory of the BEAST run directory"
    echo "  STATE_TIME_CSV  Path to state_time.csv (generated by create_mascot_xml.py)"
    exit 1
}

if [[ $# -lt 3 ]]; then
    usage
fi

BEAST_RUN_DIR="$1"
OUTPUT_DIR="$2"
STATE_TIME_CSV="$3"

# =============================================================================
# CONFIG — Analysis parameters
# =============================================================================
BEAST_SEEDS=(420001 420002 420003)

# Burnin: discard the first X% of each chain's states.
BURNIN_PCT=20

# Number of trees to subsample before treeannotator. The full combined.trees
# file can be large, need to slim down the tree file for treeannotator to handle.
THINNED_N=500

# =============================================================================
# CONFIG — Tool paths  (machine-specific)
# =============================================================================
CONDA_ENV="biopython_env"
BEAST_BIN="/Applications/BEAST 2.7.7/bin"
LOGCOMBINER="${BEAST_BIN}/logcombiner"
TREEANNOTATOR="${BEAST_BIN}/treeannotator"

# =============================================================================
# Derived paths
# =============================================================================
# Run name is derived from the BEAST run directory name.
RUN_NAME="$(basename "${BEAST_RUN_DIR}")"
DATASTREAMS_DIR="${OUTPUT_DIR}/datastreams_demes"

# All generated outputs (combined logs, trees, figures) land in a per-run
# subdirectory so multiple runs can coexist under the same OUTPUT_DIR.
RUN_OUTPUT_DIR="${OUTPUT_DIR}/${RUN_NAME}"

COMBINED_LOG="${RUN_OUTPUT_DIR}/${RUN_NAME}.combined.log"
COMBINED_TREES="${RUN_OUTPUT_DIR}/${RUN_NAME}.combined.trees"
CCD_TREE="${RUN_OUTPUT_DIR}/${RUN_NAME}.combined.mcc.trees"

# Figures go into a dedicated subfolder so they are easy to browse and don't
# clutter the combined-log directory.
FIGURES_DIR="${RUN_OUTPUT_DIR}/00_figures"

# =============================================================================
# Pre-flight checks
# =============================================================================
echo "=== Pre-flight checks ==="
for SEED in "${BEAST_SEEDS[@]}"; do
    LOG="${BEAST_RUN_DIR}/${SEED}${RUN_NAME}.log"
    if [[ ! -f "${LOG}" ]]; then
        echo "ERROR: BEAST log not found: ${LOG}"
        echo "Run Phase 4 (BEAST execution) first and verify all 3 chains completed."
        exit 1
    fi
done
mkdir -p "${RUN_OUTPUT_DIR}" "${FIGURES_DIR}"
echo "All chain logs found."
echo ""

# =============================================================================
# Step 1a: Combine main parameter logs
# =============================================================================
echo "=== Step 1a: Combine main parameter logs ==="
# -b ${BURNIN_PCT}: discard the first ${BURNIN_PCT}% of each chain as burnin.
# The three chains are combined into a single posterior sample.
INPUT_LOGS=()
for SEED in "${BEAST_SEEDS[@]}"; do
    INPUT_LOGS+=(-log "${BEAST_RUN_DIR}/${SEED}${RUN_NAME}.log")
done
"${LOGCOMBINER}" -b "${BURNIN_PCT}" \
    "${INPUT_LOGS[@]}" \
    -o "${COMBINED_LOG}"

# =============================================================================
# Step 1b: Combine NeDynamics logs (all 4 demes)
# =============================================================================
echo ""
echo "=== Step 1b: Combine NeDynamics logs ==="
# NeDynamics logs contain the skyline prevalence trajectory (I_* columns) for
# each deme — the primary output used in the prevalence trajectory figures.
# Deme4 is the outside-deme; its NeDynamics log is combined but not
# included in the cumulative incidence step.
for DEME in Deme1 Deme2 Deme3 Deme4; do
    INPUT_LOGS=()
    for SEED in "${BEAST_SEEDS[@]}"; do
        INPUT_LOGS+=(-log "${BEAST_RUN_DIR}/${SEED}${RUN_NAME}.NeDynamics.${DEME}.log")
    done
    COMBINED_NE="${RUN_OUTPUT_DIR}/${RUN_NAME}.NeDynamics.${DEME}.combined.log"
    "${LOGCOMBINER}" -b "${BURNIN_PCT}" \
        "${INPUT_LOGS[@]}" \
        -o "${COMBINED_NE}"
    echo "  Combined NeDynamics for ${DEME}: ${COMBINED_NE}"
done

# =============================================================================
# Step 1c: Combine cumulativeIncidence logs (focal demes 1–3 only)
# =============================================================================
echo ""
echo "=== Step 1c: Combine cumulativeIncidence logs ==="
# Cumulative incidence logs are only produced for sampled demes (1–3).
for DEME in Deme1 Deme2 Deme3; do
    INPUT_LOGS=()
    for SEED in "${BEAST_SEEDS[@]}"; do
        INPUT_LOGS+=(-log "${BEAST_RUN_DIR}/${SEED}${RUN_NAME}.cumulativeIncidence.${DEME}.log")
    done
    COMBINED_CI="${RUN_OUTPUT_DIR}/${RUN_NAME}.cumulativeIncidence.${DEME}.combined.log"
    "${LOGCOMBINER}" -b "${BURNIN_PCT}" \
        "${INPUT_LOGS[@]}" \
        -o "${COMBINED_CI}"
    echo "  Combined cumulativeIncidence for ${DEME}: ${COMBINED_CI}"
done

# =============================================================================
# Step 1d: Combine posterior tree distribution
# =============================================================================
echo ""
echo "=== Step 1d: Combine posterior trees ==="
INPUT_TREES=()
for SEED in "${BEAST_SEEDS[@]}"; do
    INPUT_TREES+=(-log "${BEAST_RUN_DIR}/${SEED}${RUN_NAME}.SimDataset.trees")
done
"${LOGCOMBINER}" -b "${BURNIN_PCT}" \
    "${INPUT_TREES[@]}" \
    -o "${COMBINED_TREES}"

# =============================================================================
# Step 2: Thin the combined tree file
# =============================================================================
echo ""
echo "=== Step 2: Thin combined trees to ${THINNED_N} ==="
# Count trees in the combined file (each "tree " line is one tree).
TREE_COUNT=$(grep -c "^tree " "${COMBINED_TREES}")
echo "  Combined file contains ${TREE_COUNT} trees."

if [[ "${TREE_COUNT}" -le "${THINNED_N}" ]]; then
    echo "  Fewer than ${THINNED_N} trees — skipping thinning."
    THINNED_TREES="${COMBINED_TREES}"
else
    # Reservoir-sample ${THINNED_N} trees uniformly at random, preserving
    # posterior representation without requiring treeannotator to process all trees.
    bash thin_trees.sh "${COMBINED_TREES}" "${THINNED_N}"
    # thin_trees.sh names the output: ${COMBINED_TREES%.trees}.sample${THINNED_N}.trees
    THINNED_TREES="${COMBINED_TREES%.trees}.sample${THINNED_N}.trees"
fi

# =============================================================================
# Step 3: Build consensus tree (treeannotator)
# =============================================================================
echo ""
echo "=== Step 3: treeannotator (CCD0, median heights) ==="
# -topology CCD0: Conditional Clade Distribution topology summarisation.
#   Preferred over classic MCC when the posterior tree distribution is diffuse
#   (avoids topological artefacts at poorly-supported splits).
# -height CA: 
# -burnin 0: burnin was already applied by logcombiner above.
"${TREEANNOTATOR}" \
    -burnin 0 \
    -topology MCC \
    -height keep \
    "${THINNED_TREES}" \
    "${CCD_TREE}"

# =============================================================================
# Step 4: Generate publication figures
# =============================================================================
echo ""
echo "=== Step 4: analyse_posteriors.py ==="
# Deme-to-county mapping is derived dynamically from COUNTIES_OF_INTEREST
# in filter_gisaid_metadata.py (alphabetical sort → Deme1, Deme2, …).
# The ghost / outside deme is always the last-numbered deme.
#
# Produces (all as {png,pdf}):
#   Main figures
#     - mcc_tree_deme_height_hpd
#     - migration_rates_median
#     - datastream_overview
#     - prevalence_trajectories_nedynamics_DemeN  (outside deme only)
#     - final_figure_gridspec  (tree + relative outside→local inflow +
#                               map + % introductions + datastreams)
#   Supplementary figures
#     - migration_rates_local       (local-to-local migration-rate scatter)
#     - introductions_pct           (% introductions per focal deme, stacked)
#     - introductions_vs_local_cases (intros vs β·I_local per focal deme, log y)
# Build NeDynamics and cumulative-incidence log lists dynamically from
# the number of demes in the run (detected via globbing).
NEDYN_LOGS=()
for f in "${RUN_OUTPUT_DIR}/${RUN_NAME}".NeDynamics.Deme*.combined.log; do
    [ -e "$f" ] && NEDYN_LOGS+=("$f")
done
CUMINC_LOGS=()
for f in "${RUN_OUTPUT_DIR}/${RUN_NAME}".cumulativeIncidence.Deme*.combined.log; do
    [ -e "$f" ] && CUMINC_LOGS+=("$f")
done

conda run -n "${CONDA_ENV}" python bin/analyse_posteriors.py \
    "${COMBINED_LOG}" \
    --nedynamics-log ${NEDYN_LOGS[@]} \
    --cumulative-incidence-log ${CUMINC_LOGS[@]} \
    --case-counts-csv    "${DATASTREAMS_DIR}/case_counts.csv" \
    --seroprevalence-csv "${DATASTREAMS_DIR}/seroprevalence.csv" \
    --wastewater-csv     "${DATASTREAMS_DIR}/wastewater.csv" \
    --county-populations-csv "${OUTPUT_DIR}/county_populations.csv" \
    --tree              "${CCD_TREE}" \
    --beast-xml         "${BEAST_RUN_DIR}/${RUN_NAME}.xml" \
    --state-time-csv    "${STATE_TIME_CSV}" \
    --output-dir        "${FIGURES_DIR}" \
    --burnin-fraction 0.0

# =============================================================================
# Step 5: Calculate ESS for each parameter in the combined log
# =============================================================================
echo ""
echo "=== Step 5: calculate_ESS.py ==="
# The combined log already has BURNIN_PCT% burnin applied by logcombiner, so
# pass --burnin 0.0 here to avoid double-counting. --run-name tags every row
# with the variant name so the per-variant CSVs can be concatenated downstream.
ESS_CSV="${RUN_OUTPUT_DIR}/${RUN_NAME}.ess.csv"
conda run -n "${CONDA_ENV}" python bin/calculate_ESS.py \
    "${COMBINED_LOG}" \
    --burnin 0.0 \
    --run-name "${RUN_NAME}" \
    --output "${ESS_CSV}"

echo ""
echo "=== Post-processing complete ==="
echo "Figures written to: ${FIGURES_DIR}/"
echo "ESS table written to: ${ESS_CSV}"
