name: biopython_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3
  - biopython
  - pandas
  - numpy
  - scipy
  - matplotlib
  - dendropy
  - geopandas
  - cartopy
  - contextily
  - openpyxl
  - xlrd
  - pip
  - pip:
      - baltic==0.3.0
